#:schema node_modules/wrangler/config-schema.json
name = "salary-advisor-2-0"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "salary-advisor-2-0"
database_id = "464f324e-1254-4daa-87fc-9f95b5c26a48"
